import type { Lesson, TerminalSeed } from "./types";

const BASE_DIRECTORIES: Record<string, string[]> = {
  "/": ["home", "etc", "var", "tmp", "usr"],
  "/home": ["hunter"],
  "/home/hunter": [],
  "/etc": [],
  "/var": [],
  "/tmp": [],
  "/usr": [],
};

function createSeed({
  cwd = "/home/hunter",
  directories = {},
  files = {},
}: {
  cwd?: string;
  directories?: Record<string, string[]>;
  files?: Record<string, string>;
} = {}): TerminalSeed {
  return {
    cwd,
    directories: {
      ...BASE_DIRECTORIES,
      ...directories,
    },
    files,
  };
}

function withEntries(seed: TerminalSeed, path: string, entries: string[]) {
  return {
    ...seed,
    directories: {
      ...seed.directories,
      [path]: entries,
    },
  };
}

export const lessons: Lesson[] = [
  {
    id: "1",
    title: "First Steps",
    description: "Learn how to tell where you are, what is around you, and how to move back home.",
    icon: "location",
    category: "Navigation",
    xpReward: 50,
    statReward: { type: "AGI", amount: 2 },
    difficulty: "E",
    dungeonName: "Tutorial Caves",
    terminalSeed: withEntries(createSeed(), "/home/hunter", ["sword", "shield", "potion", "README.md"]),
    steps: [
      {
        concept: "Find your current location",
        instruction: "Use the command that prints your current working directory.",
        explanation: "`pwd` answers the question 'Where am I right now?' It is one of the safest commands to run because it only displays information.",
        expectedCommand: "pwd",
        acceptedCommands: ["pwd"],
        hint: "Think: print working directory.",
        successMessage: "You now know exactly where you are standing.",
        output: "/home/hunter",
        example: "Example: `pwd`",
        whyItWorks: "`pwd` reads your shell's current location and prints the full path.",
      },
      {
        concept: "List what is in a directory",
        instruction: "List the files in the current directory to see what gear is nearby.",
        explanation: "`ls` shows the contents of a directory. It is the fastest way to inspect what files and folders exist before you do anything else.",
        expectedCommand: "ls",
        acceptedCommands: ["ls"],
        hint: "Use the list command with no extra arguments.",
        successMessage: "You scanned the room and found the available items.",
        output: "sword  shield  potion\nREADME.md",
        example: "Example: `ls`",
        whyItWorks: "With no path provided, `ls` shows the contents of your current directory.",
      },
      {
        concept: "Jump back to your home directory",
        instruction: "Return to your home directory using the shell shortcut for home.",
        explanation: "`~` is a shortcut for your home directory. Pairing it with `cd` lets you quickly return to your default workspace.",
        expectedCommand: "cd ~",
        acceptedCommands: ["cd ~", "cd /home/hunter"],
        hint: "Use `cd` and the home shortcut.",
        successMessage: "You made it back to base camp.",
        output: "",
        example: "Example: `cd ~`",
        whyItWorks: "`cd` changes your current directory, and `~` expands to your home path.",
      },
    ],
  },
  {
    id: "2",
    title: "File Forge",
    description: "Create files and folders, then confirm your work like a real shell user.",
    icon: "hammer",
    category: "Files",
    xpReward: 60,
    statReward: { type: "STR", amount: 2 },
    difficulty: "E",
    dungeonName: "Forge Depths",
    terminalSeed: withEntries(createSeed(), "/home/hunter", []),
    steps: [
      {
        concept: "Create an empty file",
        instruction: "Create a new empty file named `quest.log`.",
        explanation: "`touch` is often used to create an empty file quickly. It can also update timestamps on existing files.",
        expectedCommand: "touch quest.log",
        acceptedCommands: ["touch quest.log"],
        hint: "Use the file-creation command followed by the filename.",
        successMessage: "You forged a fresh quest log.",
        output: "",
        example: "Example: `touch quest.log`",
        whyItWorks: "`touch` creates the file if it does not already exist.",
      },
      {
        concept: "Create a directory",
        instruction: "Make a new directory named `maps` to organize your files.",
        explanation: "Directories are folders. `mkdir` creates them so your project stays organized instead of turning into one messy pile of files.",
        expectedCommand: "mkdir maps",
        acceptedCommands: ["mkdir maps"],
        hint: "Use the make-directory command.",
        successMessage: "Your storage room is ready.",
        output: "",
        example: "Example: `mkdir projects`",
        whyItWorks: "`mkdir` adds a new directory at the path you specify.",
      },
      {
        concept: "Verify results",
        instruction: "List the current directory to confirm that both the file and folder exist.",
        explanation: "A good shell habit is verifying your last action. `ls` gives you instant feedback that your command really worked.",
        expectedCommand: "ls",
        acceptedCommands: ["ls"],
        hint: "Use the listing command again.",
        successMessage: "You confirmed both items were created successfully.",
        output: "quest.log  maps",
        example: "Example: `ls`",
        whyItWorks: "Listing the directory lets you see the new file and directory side by side.",
      },
    ],
  },
  {
    id: "3",
    title: "File Operations Mastery",
    description: "Copy, rename, and remove files while learning how each action changes your workspace.",
    icon: "shuffle",
    category: "Files",
    xpReward: 70,
    statReward: { type: "STR", amount: 3 },
    difficulty: "D",
    dungeonName: "Inventory Vault",
    terminalSeed: withEntries(createSeed(), "/home/hunter", ["sword", "potion"]),
    steps: [
      {
        concept: "Copy a file",
        instruction: "Make a backup copy of `sword` called `sword.backup`.",
        explanation: "`cp` duplicates a file so you can keep the original safe while you experiment.",
        expectedCommand: "cp sword sword.backup",
        acceptedCommands: ["cp sword sword.backup"],
        hint: "`cp` needs a source and a destination.",
        successMessage: "Your backup copy is in place.",
        output: "",
        example: "Example: `cp report.txt report.bak`",
        whyItWorks: "`cp source destination` creates a second file with the destination name.",
      },
      {
        concept: "Rename or move a file",
        instruction: "Rename `sword.backup` to `iron-sword`.",
        explanation: "`mv` is used for both moving files and renaming them. If the destination is in the same folder with a new name, it acts like rename.",
        expectedCommand: "mv sword.backup iron-sword",
        acceptedCommands: ["mv sword.backup iron-sword"],
        hint: "Use the move command with the old name and new name.",
        successMessage: "The file has been renamed.",
        output: "",
        example: "Example: `mv draft.txt final.txt`",
        whyItWorks: "`mv` changes where a file lives or what it is called.",
      },
      {
        concept: "Delete a file carefully",
        instruction: "Remove the `potion` file from the directory.",
        explanation: "`rm` deletes files. Unlike many graphical file explorers, there is usually no trash can or undo, so it should be used carefully.",
        expectedCommand: "rm potion",
        acceptedCommands: ["rm potion"],
        hint: "Use the remove command with the file name.",
        successMessage: "The unneeded file is gone.",
        output: "",
        example: "Example: `rm old-log.txt`",
        whyItWorks: "`rm` removes the file entry from the filesystem.",
      },
    ],
  },
  {
    id: "4",
    title: "Text Inspection Basics",
    description: "Read files and inspect only the parts you need instead of opening everything manually.",
    icon: "document-text",
    category: "Viewing",
    xpReward: 65,
    statReward: { type: "INT", amount: 2 },
    difficulty: "D",
    dungeonName: "Library Ruins",
    terminalSeed: createSeed({
      directories: {
        "/home/hunter": ["quest.log", "maps", "enemies.txt"],
        "/home/hunter/maps": ["world.txt"],
      },
      files: {
        "/home/hunter/quest.log": "Kill 5 goblins\nFind lost relic",
        "/home/hunter/maps/world.txt": "Forest Entrance\nGoblin Camp\nMountain Pass\nAncient Ruins",
        "/home/hunter/enemies.txt":
          "goblin\norc\nskeleton\nmage\nwolf\nslime\ngoblin shaman\nbandit\norc captain\ndrake\nslime king\nlich",
      },
    }),
    steps: [
      {
        concept: "Read an entire file",
        instruction: "Display the contents of `quest.log`.",
        explanation: "`cat` prints the contents of a file to the terminal. It is useful for short files and quick checks.",
        expectedCommand: "cat quest.log",
        acceptedCommands: ["cat quest.log"],
        hint: "Use the command that prints a file's content.",
        successMessage: "You read the quest log from top to bottom.",
        output: "Kill 5 goblins\nFind lost relic",
        example: "Example: `cat README.md`",
        whyItWorks: "`cat` sends the file's text directly to standard output.",
      },
      {
        concept: "Preview the beginning of a file",
        instruction: "Show the first 3 lines of `maps/world.txt`.",
        explanation: "`head` is perfect when you only need the beginning of a file. This is useful for logs, configs, and previews.",
        expectedCommand: "head -3 maps/world.txt",
        acceptedCommands: ["head -3 maps/world.txt", "head -n 3 maps/world.txt"],
        hint: "Use `head` with an option to control the number of lines.",
        successMessage: "You previewed the top of the map file.",
        output: "Forest Entrance\nGoblin Camp\nMountain Pass",
        example: "Example: `head -5 server.log`",
        whyItWorks: "`head` limits the output to the first few lines instead of showing everything.",
      },
      {
        concept: "Count lines in a file",
        instruction: "Count how many lines are in `enemies.txt`.",
        explanation: "`wc` means word count, but with `-l` it specifically counts lines. This is handy for logs, datasets, and scripts.",
        expectedCommand: "wc -l enemies.txt",
        acceptedCommands: ["wc -l enemies.txt"],
        hint: "Use `wc` with the line-count flag.",
        successMessage: "You measured the file without reading every line.",
        output: "12 enemies.txt",
        example: "Example: `wc -l access.log`",
        whyItWorks: "The `-l` flag tells `wc` to report only line count.",
      },
    ],
  },
  {
    id: "5",
    title: "Search & Filter Power",
    description: "Search through text and combine commands to narrow down exactly what you want.",
    icon: "search",
    category: "Text",
    xpReward: 80,
    statReward: { type: "INT", amount: 3 },
    difficulty: "D",
    dungeonName: "Enemy Archives",
    terminalSeed: createSeed({
      directories: {
        "/home/hunter": ["enemies.txt"],
      },
      files: {
        "/home/hunter/enemies.txt":
          "goblin x3\norc raider\norc captain\ngoblin shaman\nslime\norc brute\norc scout\ngoblin king",
      },
    }),
    steps: [
      {
        concept: "Search for matching text",
        instruction: "Find every line in `enemies.txt` that contains the word `goblin`.",
        explanation: "`grep` searches text for a pattern and prints only the lines that match. It is one of the most useful Linux commands to learn early.",
        expectedCommand: "grep goblin enemies.txt",
        acceptedCommands: ["grep goblin enemies.txt"],
        hint: "Use `grep`, then the word to search for, then the file.",
        successMessage: "You filtered the file down to goblin lines only.",
        output: "goblin x3\ngoblin shaman",
        example: "Example: `grep ERROR app.log`",
        whyItWorks: "`grep pattern file` scans each line and prints matching ones.",
      },
      {
        concept: "Pipe one command into another",
        instruction: "Count how many lines mention `orc` in `enemies.txt`.",
        explanation: "The pipe operator `|` sends the output of one command into another. Here, `grep` finds the matching lines and `wc -l` counts them.",
        expectedCommand: "grep orc enemies.txt | wc -l",
        acceptedCommands: ["grep orc enemies.txt | wc -l"],
        hint: "Search first, then pipe the results into a line count.",
        successMessage: "You chained two commands together successfully.",
        output: "4",
        example: "Example: `grep TODO notes.txt | wc -l`",
        whyItWorks: "Pipes turn small commands into reusable building blocks.",
      },
    ],
  },
  {
    id: "6",
    title: "Pipe Power Unleashed",
    description: "Use pipes and redirection to transform output instead of just reading it.",
    icon: "git-merge",
    category: "Pipes",
    xpReward: 100,
    statReward: { type: "INT", amount: 4 },
    difficulty: "C",
    dungeonName: "Pipeline Labyrinth",
    terminalSeed: createSeed({
      directories: {
        "/home/hunter": ["quest.log", "enemies.txt", "shield", "sword"],
      },
      files: {
        "/home/hunter/quest.log": "Find relic",
        "/home/hunter/enemies.txt": "goblin\norc\nskeleton",
        "/home/hunter/shield": "bronze shield",
        "/home/hunter/sword": "iron sword",
      },
    }),
    steps: [
      {
        concept: "Filter command output",
        instruction: "List one item per line, then keep only the `.txt` entries.",
        explanation: "Many shell workflows start with one command producing data and another command filtering it. `ls -1` makes the output easier to pipe into text tools.",
        expectedCommand: "ls -1 | grep .txt",
        acceptedCommands: ["ls -1 | grep .txt"],
        hint: "You need a pipe between the list and search commands.",
        successMessage: "You filtered the list down to text files.",
        output: "quest.log\nenemies.txt",
        example: "Example: `ls -1 | grep .js`",
        whyItWorks: "`grep` reads standard input when no file argument is given.",
      },
      {
        concept: "Write command output into a file",
        instruction: "Sort the directory listing and save it to `inventory.txt`.",
        explanation: "The `>` operator redirects standard output into a file. This lets you save results instead of only printing them on screen.",
        expectedCommand: "ls | sort > inventory.txt",
        acceptedCommands: ["ls | sort > inventory.txt"],
        hint: "Use a pipe first, then redirect the final result into a file.",
        successMessage: "You created a sorted inventory file.",
        output: "",
        example: "Example: `ps aux | sort > processes.txt`",
        whyItWorks: "`>` replaces the target file with the command output.",
      },
      {
        concept: "Append instead of overwrite",
        instruction: "Add the word `Updated` to the end of `inventory.txt` without replacing the file.",
        explanation: "`>>` appends output to the end of a file. This is safer than `>` when you want to preserve existing content.",
        expectedCommand: "echo Updated >> inventory.txt",
        acceptedCommands: ["echo Updated >> inventory.txt"],
        hint: "Use `echo` plus the append redirection operator.",
        successMessage: "You added a new line without losing the original file.",
        output: "",
        example: "Example: `echo done >> deploy.log`",
        whyItWorks: "`>>` opens the file in append mode rather than overwrite mode.",
      },
    ],
  },
  {
    id: "7",
    title: "Permissions & Defense",
    description: "Check who you are and adjust file permissions to make scripts executable.",
    icon: "shield",
    category: "Permissions",
    xpReward: 90,
    statReward: { type: "DEF", amount: 4 },
    difficulty: "C",
    dungeonName: "Security Crypt",
    terminalSeed: createSeed({
      directories: {
        "/home/hunter": ["hunt.sh"],
      },
      files: {
        "/home/hunter/hunt.sh": "#!/bin/bash\necho Hunting...",
      },
    }),
    steps: [
      {
        concept: "Identify the current user",
        instruction: "Print the current username.",
        explanation: "`whoami` tells you which user account is running the current shell. That matters because permissions are tied to users and groups.",
        expectedCommand: "whoami",
        acceptedCommands: ["whoami"],
        hint: "Use the command that literally means 'who am I?'",
        successMessage: "You confirmed which account is active.",
        output: "hunter",
        example: "Example: `whoami`",
        whyItWorks: "The shell asks the system which user identity owns the current session.",
      },
      {
        concept: "Make a script executable",
        instruction: "Give execute permission to `hunt.sh`.",
        explanation: "`chmod` changes file permissions. `+x` adds execute permission so a script can be run directly.",
        expectedCommand: "chmod +x hunt.sh",
        acceptedCommands: ["chmod +x hunt.sh"],
        hint: "Use `chmod` with the execute flag.",
        successMessage: "The script can now be executed.",
        output: "",
        example: "Example: `chmod +x deploy.sh`",
        whyItWorks: "`+x` modifies the mode bits to allow execution.",
      },
    ],
  },
  {
    id: "8",
    title: "Process Hunter",
    description: "Inspect running processes and stop a misbehaving one by PID.",
    icon: "activity",
    category: "Processes",
    xpReward: 110,
    statReward: { type: "VIT", amount: 5 },
    difficulty: "C",
    dungeonName: "Process Dungeon",
    terminalSeed: withEntries(createSeed(), "/home/hunter", ["process.log"]),
    steps: [
      {
        concept: "Inspect running processes",
        instruction: "Show the full process list.",
        explanation: "`ps aux` is a common way to inspect everything currently running. It helps you diagnose stuck tasks, high CPU use, or orphaned processes.",
        expectedCommand: "ps aux",
        acceptedCommands: ["ps aux"],
        hint: "Use `ps` with the common all-process flags.",
        successMessage: "You revealed the active processes.",
        output: "USER       PID %CPU %MEM COMMAND\nhunter    1234  2.1  0.3 python bot.py",
        example: "Example: `ps aux`",
        whyItWorks: "The options tell `ps` to show a broad, detailed list of processes.",
      },
      {
        concept: "Stop a process by ID",
        instruction: "Terminate the process with PID `1234`.",
        explanation: "Every running process has a PID, or process ID. `kill` sends a signal to that process so it can stop.",
        expectedCommand: "kill 1234",
        acceptedCommands: ["kill 1234"],
        hint: "Use the kill command followed by the process ID.",
        successMessage: "The rogue process was terminated.",
        output: "",
        example: "Example: `kill 2451`",
        whyItWorks: "`kill` sends a termination signal to the process with that PID.",
      },
    ],
  },
  {
    id: "9",
    title: "Disk & Memory Scout",
    description: "Check disk and directory usage so you can see where system resources are going.",
    icon: "hard-drive",
    category: "System",
    xpReward: 95,
    statReward: { type: "VIT", amount: 4 },
    difficulty: "C",
    dungeonName: "Resource Vault",
    terminalSeed: createSeed({
      directories: {
        "/home/hunter": ["maps", "logs"],
        "/home/hunter/maps": ["world.txt"],
        "/home/hunter/logs": ["battle.log"],
      },
      files: {
        "/home/hunter/maps/world.txt": "zone data",
        "/home/hunter/logs/battle.log": "fight data",
      },
    }),
    steps: [
      {
        concept: "Check disk usage",
        instruction: "Show mounted disk usage in human-readable units.",
        explanation: "`df` reports filesystem disk usage. The `-h` flag makes sizes readable with units like MB and GB.",
        expectedCommand: "df -h",
        acceptedCommands: ["df -h"],
        hint: "Use the disk free command with human-readable output.",
        successMessage: "You inspected the system's mounted disks.",
        output: "Filesystem      Size  Used Avail Use%\n/dev/sda1        80G   52G   24G  69%",
        example: "Example: `df -h`",
        whyItWorks: "`df` summarizes filesystems instead of individual folders.",
      },
      {
        concept: "Measure directory size",
        instruction: "Show the size of everything in the current directory as short summaries.",
        explanation: "`du` measures file and directory size. Using `-s` shows summaries and `-h` makes the output readable.",
        expectedCommand: "du -sh *",
        acceptedCommands: ["du -sh *"],
        hint: "Use `du` with summary and human-readable flags.",
        successMessage: "You mapped out which folders use the most space.",
        output: "1.2M ./maps\n640K ./logs",
        example: "Example: `du -sh /var/log/*`",
        whyItWorks: "The shell expands `*` into every file and folder in the current directory.",
      },
    ],
  },
  {
    id: "10",
    title: "Git Hunter Academy",
    description: "Start reading Git state so you know what changed and where you are in history.",
    icon: "logo-github",
    category: "Git",
    xpReward: 130,
    statReward: { type: "INT", amount: 6 },
    difficulty: "B",
    dungeonName: "Repository Ruins",
    terminalSeed: createSeed({
      directories: {
        "/home/hunter": ["quest.log", ".git"],
        "/home/hunter/.git": [],
      },
      files: {
        "/home/hunter/quest.log": "Updated quest file",
      },
    }),
    steps: [
      {
        concept: "Check the working tree",
        instruction: "Show the current Git repository status.",
        explanation: "`git status` is the safest and most useful Git command for beginners. It tells you what changed, what is staged, and which branch you're on.",
        expectedCommand: "git status",
        acceptedCommands: ["git status"],
        hint: "Use the Git command that reports the current state.",
        successMessage: "You inspected the repository state.",
        output: "On branch main\nChanges not staged for commit:\n  modified: quest.log",
        example: "Example: `git status`",
        whyItWorks: "Git compares the working tree, staging area, and last commit to generate the report.",
      },
      {
        concept: "Read compact history",
        instruction: "Show the commit log in one-line format.",
        explanation: "`git log --oneline` gives a condensed history view that is easier to scan than the full default log.",
        expectedCommand: "git log --oneline",
        acceptedCommands: ["git log --oneline"],
        hint: "Use `git log` with the compact history flag.",
        successMessage: "You opened the commit history.",
        output: "abc1234 Quest update\n6de98f1 Initial dungeon setup",
        example: "Example: `git log --oneline`",
        whyItWorks: "`--oneline` tells Git to compress each commit into a short hash plus subject.",
      },
    ],
  },
  {
    id: "11",
    title: "Pathfinder Shortcuts",
    description: "Navigate faster with `..`, absolute paths, and home shortcuts.",
    icon: "navigate",
    category: "Navigation",
    xpReward: 85,
    statReward: { type: "AGI", amount: 3 },
    difficulty: "D",
    dungeonName: "Switchback Pass",
    terminalSeed: createSeed({
      cwd: "/home/hunter/projects/app",
      directories: {
        "/home/hunter": ["projects"],
        "/home/hunter/projects": ["app"],
        "/home/hunter/projects/app": ["README.md"],
      },
      files: {
        "/home/hunter/projects/app/README.md": "Path practice",
      },
    }),
    steps: [
      {
        concept: "Move up one directory",
        instruction: "Go up exactly one level from the current directory.",
        explanation: "`..` means 'the parent directory.' Pairing it with `cd` lets you move upward through the filesystem.",
        expectedCommand: "cd ..",
        acceptedCommands: ["cd .."],
        hint: "Use `cd` with the parent-directory shortcut.",
        successMessage: "You climbed up one directory level.",
        output: "",
        example: "Example: `cd ..`",
        whyItWorks: "`..` is a built-in path reference understood by the filesystem.",
      },
      {
        concept: "Use an absolute path",
        instruction: "Jump directly to `/home/hunter/projects`.",
        explanation: "An absolute path starts at `/`, the root of the filesystem. It works no matter where you currently are.",
        expectedCommand: "cd /home/hunter/projects",
        acceptedCommands: ["cd /home/hunter/projects"],
        hint: "Use `cd` with the full path starting at `/`.",
        successMessage: "You navigated with a full absolute path.",
        output: "",
        example: "Example: `cd /etc`",
        whyItWorks: "Absolute paths ignore your current location and start from the root directory.",
      },
    ],
  },
  {
    id: "12",
    title: "Tail the Story",
    description: "Read only the end of a file when the latest lines matter most.",
    icon: "reader",
    category: "Viewing",
    xpReward: 75,
    statReward: { type: "INT", amount: 3 },
    difficulty: "D",
    dungeonName: "Logwatch Keep",
    terminalSeed: createSeed({
      directories: {
        "/home/hunter": ["battle.log"],
      },
      files: {
        "/home/hunter/battle.log":
          "Entering dungeon\nScouting chamber\nBoss enraged\nPotion consumed\nVictory achieved",
      },
    }),
    steps: [
      {
        concept: "Read the last lines of a file",
        instruction: "Show the last 3 lines of `battle.log`.",
        explanation: "`tail` is the opposite of `head`. It is especially useful for logs because the newest events are usually at the bottom.",
        expectedCommand: "tail -3 battle.log",
        acceptedCommands: ["tail -3 battle.log", "tail -n 3 battle.log"],
        hint: "Use `tail` with a number of lines.",
        successMessage: "You checked the newest events in the log.",
        output: "Boss enraged\nPotion consumed\nVictory achieved",
        example: "Example: `tail -20 app.log`",
        whyItWorks: "`tail` keeps only the last requested lines of the file output.",
      },
    ],
  },
  {
    id: "13",
    title: "Redirect & Report",
    description: "Capture output into files so your commands create artifacts, not just terminal text.",
    icon: "document-attach",
    category: "Pipes",
    xpReward: 95,
    statReward: { type: "INT", amount: 4 },
    difficulty: "C",
    dungeonName: "Archive Hall",
    terminalSeed: withEntries(createSeed(), "/home/hunter", []),
    steps: [
      {
        concept: "Write generated text to a file",
        instruction: "Write `Hunter ready` into a new file called `status.txt`.",
        explanation: "Redirection turns command output into file content. This is how shell commands start creating reports, logs, and config fragments.",
        expectedCommand: "echo Hunter ready > status.txt",
        acceptedCommands: ["echo Hunter ready > status.txt"],
        hint: "Use `echo` and the overwrite redirection operator.",
        successMessage: "You created a file from command output.",
        output: "",
        example: "Example: `echo hello > greeting.txt`",
        whyItWorks: "The shell captures standard output and writes it into the target file.",
      },
      {
        concept: "Append another line",
        instruction: "Add `Quest accepted` to the end of `status.txt`.",
        explanation: "Appending is ideal when you want to keep existing data and add more to it over time.",
        expectedCommand: "echo Quest accepted >> status.txt",
        acceptedCommands: ["echo Quest accepted >> status.txt"],
        hint: "Use the append operator, not the overwrite operator.",
        successMessage: "You extended the report instead of replacing it.",
        output: "",
        example: "Example: `echo done >> run.log`",
        whyItWorks: "`>>` preserves the existing file content and writes new output at the end.",
      },
    ],
  },
  {
    id: "14",
    title: "Network Scout",
    description: "Test connectivity and fetch remote data with beginner-friendly network tools.",
    icon: "globe",
    category: "System",
    xpReward: 120,
    statReward: { type: "VIT", amount: 5 },
    difficulty: "C",
    dungeonName: "Signal Ridge",
    terminalSeed: withEntries(createSeed(), "/home/hunter", []),
    steps: [
      {
        concept: "Test whether a host is reachable",
        instruction: "Send a quick ping to `example.com`.",
        explanation: "`ping` checks whether your machine can reach a host on the network and how long the round trip takes.",
        expectedCommand: "ping example.com",
        acceptedCommands: ["ping example.com"],
        hint: "Use the network test command followed by the host name.",
        successMessage: "You verified the host was reachable.",
        output: "64 bytes from example.com: icmp_seq=1 ttl=57 time=12.4 ms",
        example: "Example: `ping github.com`",
        whyItWorks: "`ping` sends ICMP echo requests and listens for replies.",
      },
      {
        concept: "Fetch remote content",
        instruction: "Use `curl` to request `https://example.com`.",
        explanation: "`curl` makes network requests from the command line. It is commonly used for APIs, downloads, and quick HTTP tests.",
        expectedCommand: "curl https://example.com",
        acceptedCommands: ["curl https://example.com"],
        hint: "Use the transfer tool with the full URL.",
        successMessage: "You fetched content from a remote server.",
        output: "<html>\n  <title>Example Domain</title>\n</html>",
        example: "Example: `curl https://api.example.com/health`",
        whyItWorks: "`curl` opens a connection to the URL and prints the response body by default.",
      },
    ],
  },
  {
    id: "15",
    title: "Git Changes Under Control",
    description: "Track modified files and compare what changed before you commit.",
    icon: "git-compare",
    category: "Git",
    xpReward: 140,
    statReward: { type: "INT", amount: 6 },
    difficulty: "B",
    dungeonName: "Diff Bastion",
    terminalSeed: createSeed({
      directories: {
        "/home/hunter": ["quest.log", ".git"],
        "/home/hunter/.git": [],
      },
      files: {
        "/home/hunter/quest.log": "Defeat the cave troll",
      },
    }),
    steps: [
      {
        concept: "Compare current changes",
        instruction: "Show the unstaged differences in the repo.",
        explanation: "`git diff` shows exactly what lines changed. It helps you review your work before staging or committing it.",
        expectedCommand: "git diff",
        acceptedCommands: ["git diff"],
        hint: "Use the Git command that compares current changes.",
        successMessage: "You inspected the exact lines that changed.",
        output: "diff --git a/quest.log b/quest.log\n+Defeat the cave troll",
        example: "Example: `git diff`",
        whyItWorks: "Git compares the working tree against the index to produce a patch view.",
      },
      {
        concept: "Stage a file for commit",
        instruction: "Stage `quest.log` so it is ready to commit.",
        explanation: "`git add` moves a file into the staging area. Staging lets you choose exactly what will go into the next commit.",
        expectedCommand: "git add quest.log",
        acceptedCommands: ["git add quest.log"],
        hint: "Use the add command with the file name.",
        successMessage: "The file is now staged for the next commit.",
        output: "",
        example: "Example: `git add src/app.ts`",
        whyItWorks: "`git add` updates Git's index to include the current version of that file.",
      },
    ],
  },
  {
    id: "20",
    title: "Master Hacker Toolkit",
    description: "Combine find, xargs, and disk tools in a higher-level workflow.",
    icon: "construct",
    category: "Advanced",
    xpReward: 250,
    statReward: { type: "AGI", amount: 18 },
    difficulty: "A",
    dungeonName: "Binary Citadel",
    terminalSeed: createSeed({
      directories: {
        "/home/hunter": ["lib", "scripts", "tmp"],
        "/home/hunter/lib": ["utils.py"],
        "/home/hunter/scripts": ["bot.py"],
        "/home/hunter/tmp": ["cache.tmp"],
      },
      files: {
        "/home/hunter/lib/utils.py": "print('utils')",
        "/home/hunter/scripts/bot.py": "print('bot')",
        "/home/hunter/tmp/cache.tmp": "temp",
      },
    }),
    steps: [
      {
        concept: "Search recursively for files",
        instruction: "Find every Python file under the current directory.",
        explanation: "`find` walks through directories recursively. It is much more powerful than `ls` when you need to search by name or type.",
        expectedCommand: "find . -name '*.py'",
        acceptedCommands: ["find . -name '*.py'"],
        hint: "Start at the current directory and use a name filter.",
        successMessage: "You performed a recursive filename search.",
        output: "./lib/utils.py\n./scripts/bot.py",
        example: "Example: `find . -name '*.log'`",
        whyItWorks: "`find` visits each path and prints the ones that match the expression.",
      },
      {
        concept: "Send many matches into another command",
        instruction: "Find `.tmp` files and pass them into `rm` using `xargs`.",
        explanation: "`xargs` takes lines of input and turns them into command arguments. It is often used to chain search results into another tool.",
        expectedCommand: "find . -name '*.tmp' | xargs rm",
        acceptedCommands: ["find . -name '*.tmp' | xargs rm"],
        hint: "Search first, then use `xargs` to build the remove command.",
        successMessage: "You combined discovery and action in one pipeline.",
        output: "",
        example: "Example: `find . -name '*.log' | xargs wc -l`",
        whyItWorks: "`xargs` converts the piped list into arguments for the next command.",
      },
      {
        concept: "Summarize directory sizes",
        instruction: "Show human-readable sizes for each folder in `/home`.",
        explanation: "This type of summary is useful when you are diagnosing where disk space is going across multiple users or projects.",
        expectedCommand: "du -sh /home/*",
        acceptedCommands: ["du -sh /home/*"],
        hint: "Use `du` with summary mode against every folder in `/home`.",
        successMessage: "You generated a cross-directory storage report.",
        output: "1.2G /home/hunter\n500M /home/shared",
        example: "Example: `du -sh /var/*`",
        whyItWorks: "The shell expands `/home/*` into each directory, and `du` summarizes them one by one.",
      },
    ],
  },
];

export function getNextLessonRecommendation(completedLessons: string[]) {
  return lessons.find((lesson) => !completedLessons.includes(lesson.id)) ?? null;
}
