import type { ShopItem } from "./types";

export const shopItems: ShopItem[] = [
  {
    id: "title_shadow_recruit",
    title: "Shadow Recruit",
    description: "A title for hunters just beginning to awaken.",
    cost: 30,
    icon: "moon",
    color: "#64D2FF",
    category: "title",
    unlockValue: "Shadow Recruit",
  },
  {
    id: "title_gatebreaker",
    title: "Gatebreaker",
    description: "A sharper title for hunters who clear content aggressively.",
    cost: 55,
    icon: "flash",
    color: "#FF8A5B",
    category: "title",
    unlockValue: "Gatebreaker",
  },
  {
    id: "title_monarch_heir",
    title: "Monarch Heir",
    description: "A rare title for players chasing a darker power fantasy.",
    cost: 85,
    icon: "diamond",
    color: "#FF2D55",
    category: "title",
    unlockValue: "Monarch Heir",
  },
  {
    id: "frame_neon_hunt",
    title: "Neon Hunt Frame",
    description: "Bright cyan framing for a cleaner hunter profile.",
    cost: 40,
    icon: "square-outline",
    color: "#64D2FF",
    category: "frame",
    unlockValue: "neon",
  },
  {
    id: "frame_ember_guard",
    title: "Ember Guard Frame",
    description: "Burning orange profile trim for a more dangerous look.",
    cost: 60,
    icon: "flame",
    color: "#FF8A5B",
    category: "frame",
    unlockValue: "ember",
  },
  {
    id: "theme_shadowcore",
    title: "Shadowcore Terminal",
    description: "Dark purple-black shell with cold blue prompt glow.",
    cost: 45,
    icon: "terminal",
    color: "#8B5CF6",
    category: "theme",
    unlockValue: "shadowcore",
    preview: "hunter@system:~$ shadows rise",
  },
  {
    id: "theme_frostbyte",
    title: "Frostbyte Terminal",
    description: "Icy cyan terminal theme with crisp output contrast.",
    cost: 55,
    icon: "snow",
    color: "#64D2FF",
    category: "theme",
    unlockValue: "frostbyte",
    preview: "hunter@system:~$ scan complete",
  },
  {
    id: "theme_emberline",
    title: "Emberline Terminal",
    description: "Heat-tinted terminal styling with fiery command feedback.",
    cost: 65,
    icon: "flame",
    color: "#FF8A5B",
    category: "theme",
    unlockValue: "emberline",
    preview: "hunter@system:~$ ignition ready",
  },
];

export const defaultOwnedTitles = ["Novice"];
export const defaultOwnedFrames = ["default"];
export const defaultOwnedThemes = ["default"];
